const defaultColors = [
    "#5A2CDD",
    "#43A4AA",
    "#F36B24",
    "#ABCBFB",
    "#B5DCFF",
    "#DEB4FF",
    "#F0C6FA",
    "#FAC6E5",
    "#FCCBBC",
    "#FEDAB7",
    "#BEEAC8",
    "#CDEBAE",
    "#E6E3A6",
    "#DED3AC",
    "#5A2CDD",
    "#43A4AA",
    "#F36B24",
    "#ABCBFB",
    "#B5DCFF",
    "#DEB4FF",
    "#F0C6FA",
    "#FAC6E5",
    "#FCCBBC",
    "#FEDAB7",
    "#BEEAC8",
    "#CDEBAE",
    "#E6E3A6",
    "#DED3AC",
    "#5A2CDD",
    "#43A4AA"
];

export default defaultColors;